name: build app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build APK
      run: ./gradlew assembleRelease
      
    - name: Build AAB
      run: ./gradlew bundleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/**/*.apk
    
    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-bundle
        path: app/build/outputs/bundle/release/app-release.aab

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_apk
      env:
        BUILD_TOOLS_VERSION: "34.0.0"
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Example Release
      uses: actions/upload-artifact@v4
      with:
        name: app-release-signed
        files: |
          ${{ steps.sign_app.signedReleaseFile0 }}
          ${{ steps.sign_app.signedReleaseFile1 }}
          ${{ steps.sign_app.signedReleaseFile2 }}
